feat: add auth0 wrapper
supabase/wrappers pull request #183
Opened 2023-10-26 01:10 UTC by J0

## What kind of change does this PR introduce?

Possible POC around an auth0 wrapper for continuous migration from Auth0 to Supabase Auth. Done as a side project

2023-11-09 04:53 UTC, imor commented on wrappers/src/fdw/auth0_fdw/auth0_client/mod.rs
> +    pub fn get_client(&self) -> ClientWithMiddleware {
`get_client` can return a reference to `ClientWithMiddleware` instead of returning an owned value. This puts control in the callers hand. If the caller can work with a reference, great. If not, they can still clone it.

2023-11-09 04:53 UTC, imor commented on wrappers/src/fdw/auth0_fdw/auth0_client/rows_iterator.rs
> +    qdrant_client: Auth0Client,
rename to `auth0_client`?

2023-11-09 04:53 UTC, imor commented on wrappers/src/fdw/auth0_fdw/result.rs
> +struct Auth0FieldsVisitor {
`Auth0FieldsVisitor` can be removed. Deriving the `Deserialize` trait should be enough to deserialize the json response from the API. Similarly, manual impl of `Deserialize` on `Auth0Fields` below is not needed.

2023-11-22 10:41 UTC, J0 commented on wrappers/dockerfiles/auth0/server.py
> +        # TODO: Update this server data with relevant info
```suggestion
```

2023-11-22 10:42 UTC, J0 commented on wrappers/src/fdw/auth0_fdw/auth0_client/mod.rs
> +// TODO: Remove this and replace new() with Auth0ClientError
```suggestion
```

2023-11-22 10:42 UTC, J0 commented on wrappers/src/fdw/auth0_fdw/result.rs
> +                // let timestamp_option = Timestamp::from_str(&self.created_at).ok();
```suggestion
```

2023-11-23 03:14 UTC, burmecia commented on wrappers/src/fdw/auth0_fdw/auth0_fdw.rs
> +// A simple demo FDW
can we remove this comment, as it is not a simple demo anymore.

2023-11-23 03:14 UTC, burmecia commented on wrappers/src/fdw/auth0_fdw/auth0_client/mod.rs
can we run `cargo fmt` to format code before commit? And also run `cargo clippy --features auth0_fdw` to make clippy happy :paperclip:.

2023-12-01 07:18 UTC, imor requested changes

2023-12-01 07:18 UTC, imor commented on wrappers/src/fdw/auth0_fdw/auth0_client/mod.rs
> +}
`_url` and `_runtime` are not being used anywhere. Compared with `qdrant_fdw` which inspired this impl the difference is that this impl doesn't have a method similar to [`fetch_points`](https://github.com/supabase/wrappers/blob/b93b20c8d06cb86666bd12a50e6ff6975982c7eb/wrappers/src/fdw/qdrant_fdw/qdrant_client/mod.rs#L34-L56) where `_url` and `_runtime` could be used.

The bulk of logic in `begin_scan`/`iter_scan` methods can be moved here in a `fetch_x` method which will make those methods very simple as seen in [`qdrant_fdw`'s impl of those methods](https://github.com/supabase/wrappers/blob/b93b20c8d06cb86666bd12a50e6ff6975982c7eb/wrappers/src/fdw/qdrant_fdw/qdrant_fdw.rs#L109-L142).

The idea of `RowsIterator` (which is not being used anywhere) was to provide a batching abstraction which will make `begin_scan`/`iter_scan` impls simpler.

@J0 let me know if you need any help in making the code work with these ideas.

2023-12-01 07:18 UTC, imor commented on wrappers/src/fdw/auth0_fdw/auth0_client/rows_iterator.rs
> +use crate::fdw::auth0_fdw::auth0_client::{Auth0Client, Auth0ClientError};
The `RowsIterator` impl is not being used anywhere.

2023-12-01 07:18 UTC, imor commented on wrappers/src/fdw/auth0_fdw/auth0_fdw.rs
> +    client: Option<Auth0Client>,
`client` can be a `Auth0Client` instead of `Option<Auth0Client>` because when `Auth0Fdw` is constructed in the `new` method below and `Auth0Client` is already available.

2023-12-04 12:30 UTC, burmecia approved these changes

2023-12-04 12:30 UTC, burmecia commented on wrappers/src/fdw/auth0_fdw/auth0_fdw.rs
> +    const FDW_NAME: &str = "Auth0Fdw";
Can we make it static string? e.g. `const FDW_NAME: &'static str = "Auth0Fdw";`. This is to remove compilation warning when using latest rust.

2023-12-05 04:40 UTC, burmecia commented
Can you upgrade Rust to v1.74.0 and remove warnings outputted by  `cargo clippy --features auth0_fdw`?

2023-12-05 08:11 UTC, J0 commented
patched the errors but still need to refactor the codebase as a whole. Will try to find time for it this evening or tomorrow morning

2023-12-08 14:58 UTC, J0 commented
As discussed will merge for now and address 

1. reinstate the statistics
2. Add proper logic around have_more_rows and next_page_offset
3. Add all relevant fields

As a stretch we will also add support for other objects and push down qualifiers/search queries which involve multiple objects.

Very appreciative of @imor for help with pushing this through. Thanks so much!

2023-12-08 14:58 UTC, merged